/**
 * generated by Xtext 2.31.0.M3
 */
package br.ufscar.dc.compiladores.alguma.alguma;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fator Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufscar.dc.compiladores.alguma.alguma.AlgumaPackage#getFatorAritmetico()
 * @model
 * @generated
 */
public interface FatorAritmetico extends EObject
{
} // FatorAritmetico
