/*
 * generated by Xtext 2.31.0.M3
 */
package br.ufscar.dc.compiladores.alguma;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlgumaRuntimeModule extends AbstractAlgumaRuntimeModule {
}
