/*
 * generated by Xtext 2.31.0.M3
 */
package br.ufscar.dc.compiladores.alguma.ide;


/**
 * Use this class to register ide components.
 */
public class AlgumaIdeModule extends AbstractAlgumaIdeModule {
}
